enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
    cmd-1 = 'workspace 1' # coding
    cmd-2 = 'workspace 2' # browser
    cmd-3 = 'workspace 3' # notes
    cmd-4 = 'workspace 4' # chats
    cmd-0 = 'workspace 5' # others

    cmd-shift-1 = 'move-node-to-workspace 1'
    cmd-shift-2 = 'move-node-to-workspace 2'
    cmd-shift-3 = 'move-node-to-workspace 3'
    cmd-shift-4 = 'move-node-to-workspace 4'
    cmd-shift-0 = 'move-node-to-workspace 5'
